# Generated by Django 2.1.5 on 2019-02-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190226_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='uploadfrom',
        ),
    ]
