# Generated by Django 2.1.5 on 2019-02-26 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likedpost',
            field=models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
