# Generated by Django 2.1.5 on 2019-02-26 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_auto_20190226_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='userlike',
        ),
        migrations.AddField(
            model_name='post',
            name='likedpost',
            field=models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
